#!/usr/bin/env python3
"""Generate a Clash / mihomo proxy list from validated proxies.

Reads the flat address files produced by this project's exporter
(``data/valid_http.txt``, ``data/valid_socks5.txt``) and writes a Clash
config *fragment* (``data/clash_proxies.yaml``) containing a ``proxies:``
list plus a ``proxy-groups:`` entry that bundles them.

This script ONLY writes files. It does not touch system proxy settings,
environment variables, git/brew config, or any running proxy client.
On a fresh system with Clash/mihomo, merge this fragment into your config
or load it as a file-based ``proxy-provider``.

Usage:
    python scripts/gen_clash.py [--data-dir data] [--out data/clash_proxies.yaml]
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

ADDR_RE = re.compile(r"^(?P<proto>https?|socks5)://(?P<host>[^:/]+):(?P<port>\d+)/?$")


def _parse(path: Path, clash_type: str) -> list[dict]:
    """Parse a flat address file into Clash proxy node dicts."""
    nodes: list[dict] = []
    if not path.exists():
        return nodes
    seen: set[str] = set()
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        m = ADDR_RE.match(line)
        if not m:
            continue
        host, port = m.group("host"), int(m.group("port"))
        name = f"{clash_type}-{host}:{port}"
        if name in seen:
            continue
        seen.add(name)
        nodes.append(
            {
                "name": name,
                "type": clash_type,
                "server": host,
                "port": port,
                "udp": True,
            }
        )
    return nodes


def _yaml_scalar(value) -> str:  # noqa: ANN001
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def _emit_nodes(nodes: list[dict]) -> list[str]:
    lines: list[str] = []
    for n in nodes:
        lines.append(f"  - name: {n['name']}")
        lines.append(f"    type: {n['type']}")
        lines.append(f"    server: {n['server']}")
        lines.append(f"    port: {n['port']}")
        lines.append(f"    udp: {_yaml_scalar(n['udp'])}")
    return lines


def main() -> None:
    """Generate a Clash/mihomo proxy list from this project's validated proxies.

    Reads data/valid_*.txt and writes data/clash_proxies.yaml. Pure file output;
    no system proxy settings, env vars, or running clients are touched.
    """
    parser = argparse.ArgumentParser(description="Generate Clash proxy list from validated proxies")
    parser.add_argument("--data-dir", default="data", help="Directory with valid_*.txt files")
    parser.add_argument(
        "--out",
        default=None,
        help="Output YAML path (default: <data-dir>/clash_proxies.yaml)",
    )
    args = parser.parse_args()

    data_dir = Path(args.data_dir)
    out_path = Path(args.out) if args.out else data_dir / "clash_proxies.yaml"

    http_nodes = _parse(data_dir / "valid_http.txt", "http")
    https_nodes = _parse(data_dir / "valid_https.txt", "http")  # Clash uses type http for https too
    socks5_nodes = _parse(data_dir / "valid_socks5.txt", "socks5")

    nodes = http_nodes + https_nodes + socks5_nodes
    if not nodes:
        print(f"No validated proxies found in {data_dir} (run `python main.py validate` first)")
        return

    all_names = [n["name"] for n in nodes]
    lines: list[str] = []
    lines.append("# Generated by scripts/gen_clash.py — merge into your Clash/mihomo config")
    lines.append("# or load as a file-based proxy-provider. Pure artifact; no system changes made.")
    lines.append("proxies:")
    lines.extend(_emit_nodes(nodes))
    lines.append("")
    lines.append("proxy-groups:")
    lines.append("  - name: ValidatedPool")
    lines.append("    type: select")
    lines.append("    proxies:")
    lines.append("      - DIRECT")
    lines.extend(f"      - {name}" for name in all_names)
    lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(
        f"Wrote {len(nodes)} proxies "
        f"({len(http_nodes)} http, {len(socks5_nodes)} socks5) -> {out_path}"
    )


if __name__ == "__main__":
    main()
